### ISSUE TITLE
SVN checkout not working anymore

### ISSUE THREAD

**Issue by FranzForstmayr** [modm-io/cmsis-header-stm32#9]
Hi, 

when starting for https://github.com/modm-io/modm/issues/1198 I noticed that stm32u0 header files are not available in this repo yet.
However, the update script does not work anymore, as the svn checkout possibilty was removed from github ([Blog](https://github.blog/news-insights/product-news/sunsetting-subversion-support/)).

I thought of changing the checkout process to some git based fetcher, or adding the relevant hal drivers directly as a git submodule for each family. (Like this one https://github.com/STMicroelectronics/stm32u0xx_hal_driver).

Any opinions? 
With the git based fetcher, the overall update process would be identical to now, but personally I think the submodules would do the job as well without big efforts.

**Comment by salkinium** [comment]
I fixed that already: https://github.com/modm-io/cmsis-header-stm32/commit/5fc97be9d1b4d16ba98673419b96ae9434455ac8
You're probably working on an old version of the repo.

The STM32U0 headers are available here: https://github.com/modm-io/cmsis-header-stm32/tree/master/stm32u0xx/Include

**Comment by salkinium** [comment]
But some of the documentation is still pointing to the old repos and the licence actually changed from Apache to BSD. 😬  I need to fix that.

**Comment by FranzForstmayr** [comment]
Ah sorry, I meant to create the issue in this repo.
https://github.com/modm-ext/stm32-cube-hal-drivers

You can close here, I had not recognized that there a two very similar repositories.
stm32u0 is missing here https://github.com/modm-ext/stm32-cube-hal-drivers

**Comment by salkinium** [comment]
Oh no, completely forgot about that repo, of course you need that for modm-devices 🤦

**Comment by salkinium** [comment]
Moved to https://github.com/modm-ext/stm32-cube-hal-drivers/pull/2
